### ISSUE TITLE
[Feature request] shadowsocks-libev version 4.0.0

### ISSUE THREAD

**Issue by PantherJohn** [shadowsocks/shadowsocks-libev#2419]
@madeye The source code is available [here](https://github.com/eLitetInc/shadowsocks-libev). Please feel free to submit issues HERE if it just simply doesn’t work. Note that I’m still working hard on it so bugs might creep in if you don’t pay much attention on them.

## Features
- [x] Users may now specify multiple servers with different encryption methods directly in the JSON-formatted config file
- [x] TCP AND UDP protocol: ACL load-balancing based on user request (domain name and ip address)
- [x] Remote domain resolution can be disabled by passing `-D` option to the main program
- [x] QUIC domain name detection is made possible by rewriting the `udprelay` module 
- [x] **PROTOCOL CHANGES!** <br/>The way shadowsocks handles UDP requests now resembles that of TCP, in which each connection is independent of each other (loosely following a-connection-is-a-connection principle) Some CAVEATS here: both the server and the client must be updated in order for you to enjoy the reduced protocol overhead and remote domain resolution under the hood of UDP

## TODO list
- [ ] Fix segfault and memory management issues using `-fsanitize=address -ggdb`
- [ ] QUIC support for UDP relay
- [ ] Library interface for all four modules including `ss-local`, `ss-redir`, `ss-tunnel`, and `ss-server`
- [ ] Enhanced domain matching algorithms for ACL
- [ ] Deprecate `ss-manager`
- [ ] Modern interface for shadowsocks server management 
- [ ] Introducing TCP pre-connect, an alternative to TCP Fast Open and connection multiplexing. Like many algorithms mentioned before, TCP pre-connect bypasses the infamous three-way handshake at the cost of increased overhead (more idle connections established before the actual data transfer starts).

### What version of shadowsocks-libev are you using?
3.2.5

### What operating system are you using?
Linux anyways

### What did you do?
idk I felt bored.

### What did you expect to see?
Some shiny new features

### What did you see instead?
Umm

### What is your config in detail (with all sensitive info masked)?
delegation.acl
```
[bypass_list]
127.0.0.1
(^|\.)bing\.com$

[proxy_list: Seattle, WA]
(^|\.)edu$
(^|\.)google\.com$
```
foobar.json
```
{
    "server": [{
        "tag": "Seattle, WA",
        "address": "example.org",
        "port": 42116
    }],
    "local_address": "0.0.0.0",
    "server_port":8388,
    "local_port":"socks",
    "password":"barfoo!",
    "timeout":60,
    "method":"rc4-md5"
}
```
```
ss-redir -c foobar.json --acl delegation.acl -u
```

**Comment by madeye** [comment]
Contributions are welcome!

But any protocol related changes are not likely to be merged, including

1. TCP pre-connect.
2. Multiplexing.
3. UDP over TCP.

For 1 and 2, please use our existing SIP003 plugin instead (v2ray-plugin). For 3, you can keep it in your fork.

Instead, some changes are likely to be merged from high priority to low.

1. Refactor of TCP relay
2. Refactor of command line parser.
3. Multiple upstream support.
4. ACL enhancement.

**Comment by PantherJohn** [comment]
@madeye Si.
okay there's a misunderstanding here. 
### 3. UDP over TCP
> The way shadowsocks handles UDP requests now resembles that of TCP.

by saying that, I basically meant that for each client request, UDP sender and receiver would use the same file descriptor with the hope that "connection" tracking would be easier, since we don't have to use hash tables to cache request information when receiving the data, not knowing where it comes from.

**Comment by qiuzi** [comment]
希望增加单端口多用户功能

**Comment by PantherJohn** [comment]
@qiuzi Can you please elaborate a bit more? I didn’t get your point. You better also post a sample config file here.

**Comment by qiuzi** [comment]
@PantherJohn 
Unblock IP, use simple-obfs combined with CDN, but now only allow "port=password"

**Comment by madeye** [comment]
Please keep developing as a fork. I'll consider merging any change from your side, if there's anything useful.
